// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// parse_request
List parse_request(String req);
RcppExport SEXP _construe_parse_request(SEXP reqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type req(reqSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_request(req));
    return rcpp_result_gen;
END_RCPP
}
// parse_response
List parse_response(String resp);
RcppExport SEXP _construe_parse_response(SEXP respSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type resp(respSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_response(resp));
    return rcpp_result_gen;
END_RCPP
}
// parse_url
DataFrame parse_url(std::vector < std::string > urls);
RcppExport SEXP _construe_parse_url(SEXP urlsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector < std::string > >::type urls(urlsSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_url(urls));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_construe_parse_request", (DL_FUNC) &_construe_parse_request, 1},
    {"_construe_parse_response", (DL_FUNC) &_construe_parse_response, 1},
    {"_construe_parse_url", (DL_FUNC) &_construe_parse_url, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_construe(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
