# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Parse an HTTP request
#'
#' @param req HTTP request character string
#' @export
parse_request <- function(req) {
    .Call(`_construe_parse_request`, req)
}

#' Parse an HTTP response
#'
#' @param resp HTTP response character string
#' @export
parse_response <- function(resp) {
    .Call(`_construe_parse_response`, resp)
}

#' Parse URLs
#'
#' @param urls character vector of URLs
#' @export
parse_url <- function(urls) {
    .Call(`_construe_parse_url`, urls)
}

